# Generated by Django 4.1.5 on 2023-02-09 12:08

from django.db import migrations
import os

with (
    open(os.path.join(os.path.dirname(__file__), "0003_create_trigger.sql"),
         encoding="UTF-8", mode="r") as migration,
    open(os.path.join(os.path.dirname(__file__), "0003_reverse_create_trigger.sql"),
         encoding="UTF-8", mode="r") as reverse_migration
):
    create_triggers_sql = migration.read()
    reverse_create_triggers_sql = reverse_migration.read()



class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0002_questionvector_and_more'),
    ]

    operations = [
        migrations.RunSQL(sql=create_triggers_sql, reverse_sql=reverse_create_triggers_sql),
    ]
