repos:
  - repo: https://github.com/pycqa/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
        language_version: python3.11.4
        entry: flake8 .
  - repo: https://github.com/psf/black
    rev: '23.3.0'
    hooks:
      - id: black
        language_version: python3.11.4
        entry: black .
        args: ["--check"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        entry: isort .
        args: ["--check"]
        pass_filenames: false
