# Generated by Django 4.1.5 on 2023-02-09 10:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_and_text', django.contrib.postgres.search.SearchVectorField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
        migrations.AddIndex(
            model_name='questionvector',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_and_text'], name='polls_quest_title_a_3fde25_gin'),
        ),
    ]
