# Generated by Django 4.2.3 on 2023-08-01 14:19

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_choice_created_choice_modified_question_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionvector',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='questionvector',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
