# Generated by Django 4.2.3 on 2023-08-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_questionvector_created_questionvector_modified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionVector',
        ),
    ]
