# Generated by Django 4.1 on 2022-09-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_slug',
            field=models.SlugField(default='', max_length=70, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='slug', max_length=40),
            preserve_default=False,
        ),
    ]
