# Generated by Django 4.1 on 2022-09-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_question_slug_question_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_slug',
            field=models.SlugField(max_length=60, unique=True, verbose_name='URL'),
        ),
    ]
