# Generated by Django 4.1 on 2022-09-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_uuid',
            field=models.UUIDField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
