# Generated by Django 4.1 on 2022-09-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_choice_choice_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_uuid',
            field=models.UUIDField(auto_created=True, unique=True),
        ),
    ]
