# Generated by Django 4.1 on 2022-09-09 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_choice_choice_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_uuid',
            field=models.UUIDField(default=uuid.UUID('412dd072-4338-4e48-ac02-4d046b1142d3'), unique=True),
        ),
    ]
