# Generated by Django 4.1 on 2022-09-13 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_choice_choice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
