# Generated by Django 4.1 on 2022-09-13 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_choice_choice_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_uuid',
            field=models.UUIDField(default=uuid.UUID('990a0533-4489-497e-bd33-8f483aab22c9')),
        ),
    ]
