# Generated by Django 4.1 on 2022-09-13 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_choice_choice_text_alter_choice_choice_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
