# Generated by Django 4.1 on 2022-09-13 13:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_choice_choice_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('choice_text', 'question')},
        ),
    ]
