# Generated by Django 4.1 on 2022-09-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_question_pub_date_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
