# Generated by Django 4.2.7 on 2023-11-19 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(limit_value=20, message='Question title must be at least 20 characters long.'), django.core.validators.MaxLengthValidator(limit_value=40, message='Question title must be no longer than 40 characters long.')]),
        ),
    ]
