# Generated by Django 4.2.3 on 2023-08-01 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_questionvector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionvector',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search', to='polls.question'),
        ),
    ]
