# Generated by Django 4.2.3 on 2023-08-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_delete_questionvector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
