# Generated by Django 4.2.3 on 2023-08-02 14:21

from django.db import migrations
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_choice_question_remove_vote_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='id',
        ),
        migrations.AddField(
            model_name='choice',
            name='fake_id',
            field=model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='question',
            name='fake_id',
            field=model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='fake_id',
            field=model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
