CHOICE_TEXT_MIN_LEN = 1
CHOICE_TEXT_MAX_LEN = 60
CHOICES_MIN_NUMBER = 2
CHOICES_MAX_NUMBER = 10
QUESTION_TITLE_MIN_LEN = 40
QUESTION_TITLE_MAX_LEN = 40
QUESTION_TEXT_MIN_LEN = 20
QUESTION_TEXT_MAX_LEN = 200
