name: Django CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: drf-polls-api
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.10" ]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports: ['5432:5432']

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Performs a clean installation of all dependencies in the `requirements/dev.txt` file
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/base.txt -r requirements/local.txt

      - name: Run flake8
        uses: py-actions/flake8@v2

      - name: Run black
        uses: psf/black@stable

      - name: Run isort
        uses: isort/isort-action@master

      - name: Run tests with coverage
        env:
          DB_ENGINE: django.db.backends.postgresql_psycopg2
          DB_HOST: localhost
          DB_NAME: postgres
          DB_PASSWORD: postgres
          DB_PORT: 5432
          DB_USER: postgres
        run: |
          python manage.py migrate
          coverage run -m pytest src\tests
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
