name: Lint

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.2"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

      - name: Run flake8
        uses: py-actions/flake8@v2

      - name: Run black
        uses: psf/black@stable

      - name: Run isort
        uses: isort/isort-action@master
